before:
  hooks:
    - go mod tidy

release:
  prerelease: auto
  make_latest: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: ois
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: ois
    tap:
      owner: NipulM
      name: homebrew-ois
      token: "{{ .Env.HOMEBREW_OIS_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/NipulM/oisbase
    description: "Orchestrated Infrastructure Scaffolder - Generate production-ready Terraform for Cloud Infrastructure"
    install: |
      bin.install "ois"
